# Generated by Django 6.0.2 on 2026-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
